version: '3.8'

services:
  web:
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/logging_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logging_db
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
